version: "3"
services:
  db:
    image:  postgres
    ports:
      - "5432:5432"
    environment:
       POSTGRES_PASSWORD: pass123
  pgadmin:
     image: dpage/pgadmin4
     ports:
       - "80:80"
     environment:
       PGADMIN_DEFAULT_EMAIL: arudenko@virtido.com
       PGADMIN_DEFAULT_PASSWORD: admin